// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SmartDoorLock

#include "../ui.h"

void ui_whiteScreen_screen_init(void)
{
    ui_whiteScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_whiteScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

}
