// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SmartDoorLock

#ifndef _SMARTDOORLOCK_UI_H
#define _SMARTDOORLOCK_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
void left_Animation(lv_obj_t * TargetObject, int delay);
void right_Animation(lv_obj_t * TargetObject, int delay);
void opacity_Animation(lv_obj_t * TargetObject, int delay);
void keyboard_down_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_start
void ui_start_screen_init(void);
void ui_event_start(lv_event_t * e);
extern lv_obj_t * ui_start;
extern lv_obj_t * ui_Label4;
// SCREEN: ui_userScreen
void ui_userScreen_screen_init(void);
void ui_event_userScreen(lv_event_t * e);
extern lv_obj_t * ui_userScreen;
void ui_event_enterpassword(lv_event_t * e);
extern lv_obj_t * ui_enterpassword;
extern lv_obj_t * ui_Label3;
void ui_event_camera(lv_event_t * e);
extern lv_obj_t * ui_camera;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_humi;
// SCREEN: ui_passwordScreen
void ui_passwordScreen_screen_init(void);
void ui_event_passwordScreen(lv_event_t * e);
extern lv_obj_t * ui_passwordScreen;
extern lv_obj_t * ui_TextArea2;
void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
extern lv_obj_t * ui_Label2;
// SCREEN: ui_adminScreen
void ui_adminScreen_screen_init(void);
void ui_event_adminScreen(lv_event_t * e);
extern lv_obj_t * ui_adminScreen;
extern lv_obj_t * ui_Panel2;
void ui_event_addfingerprintButton(lv_event_t * e);
extern lv_obj_t * ui_addfingerprintButton;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_addfingerprinting;
void ui_event_ChangePasswordButton(lv_event_t * e);
extern lv_obj_t * ui_ChangePasswordButton;
extern lv_obj_t * ui_Label6;
void ui_event_emptyallfingerprintButton(lv_event_t * e);
extern lv_obj_t * ui_emptyallfingerprintButton;
extern lv_obj_t * ui_Label8;
void ui_event_backButton(lv_event_t * e);
extern lv_obj_t * ui_backButton;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_chinese);
LV_FONT_DECLARE(ui_font_chinese24);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
