// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: SmartDoorLock

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void screen1_init(lv_event_t * e);
void submit_password(lv_event_t * e);
void screen2_init(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
